# 本地构建覆盖文件
# 使用方式：
#   docker compose -f docker-compose.yml -f docker-compose.build.yml up -d --build

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_REGISTRY_URL: ${NODE_REGISTRY_URL:-https://registry.npmmirror.com}
        MAVEN_MIRROR_ID: ${MAVEN_MIRROR_ID:-custom-maven-mirror}
        MAVEN_MIRROR_URL: ${MAVEN_MIRROR_URL:-https://repo.maven.apache.org/maven2}
