<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mars</groupId>
        <artifactId>mars-core</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>mars-mall</artifactId>
    <packaging>jar</packaging>
    <name>Mars Mall</name>
    <description>商城模块 - 商品、订单、会员、购物车</description>

    <dependencies>
        <!-- 依赖系统模块 -->
        <dependency>
            <groupId>com.mars</groupId>
            <artifactId>mars-system</artifactId>
        </dependency>
        <!-- 依赖支付模块 -->
        <dependency>
            <groupId>com.mars</groupId>
            <artifactId>mars-pay</artifactId>
        </dependency>

        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
    </dependencies>
</project>
